spring.application.name=chat-service
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat-services-DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@2005}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=1
spring.kafka.producer.properties.max.block.ms=3000

kafka.topics.message=message-topic
kafka.topics.group-message=group-message-topic
kafka.topics.read-receipt=read-receipt-topic

jwt.jwtSecret=${JWT_SECRET:Aditya@hepJFROXcyu1XqolVEXkwj/5byy59wkTuKdoWZbEy04PygDtEcaqvr4zPco#}

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}}
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.instance.preferIpAddress=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=localhost
eureka.instance.instanceId=${EUREKA_INSTANCE_ID:localhost:${spring.application.name}:${server.port}}

spring.boot.admin.client.url=${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:8090}
spring.boot.admin.client.username=${SPRING_BOOT_ADMIN_CLIENT_USERNAME:admin}
spring.boot.admin.client.password=${SPRING_BOOT_ADMIN_CLIENT_PASSWORD:admin123}
spring.boot.admin.client.instance.service-base-url=${SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL:http://localhost:${server.port}}
spring.boot.admin.client.connect-timeout=2000
spring.boot.admin.client.read-timeout=2000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

logging.level.com.chatapp.chat=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.web.socket=DEBUG