spring.application.name=auth-service
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Auth-service-DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@2005}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}}
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=localhost

jwt.jwtSecret=${JWT_SECRET:Aditya@hepJFROXcyu1XqolVEXkwj/5byy59wkTuKdoWZbEy04PygDtEcaqvr4zPco#}
jwt.accessTokenExpiration=1800000
jwt.refreshTokenExpiration=604800000

spring.security.oauth2.client.registration.google.client-id=989116835887-pkmnbj6eno70tolihifetavc0r9kpcku.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajshrivastav1456@gmail.com
spring.mail.password=hmwg clre cjaa eibh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


app.frontend.url=http://localhost:3000

#spring.boot.admin.client.url=http://localhost:8090
#spring.boot.admin.client.username=admin
#spring.boot.admin.client.password=admin123

spring.boot.admin.client.instance.service-base-url=http://localhost:${server.port}
spring.boot.admin.client.connect-timeout=2000
spring.boot.admin.client.read-timeout=2000
management.info.env.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.com.Chat_app.Auth_service=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
