spring.application.name=api-gateway

server.port=8080
spring.main.web-application-type=reactive


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}}
eureka.instance.prefer-ip-address=true

jwt.jwtSecret=${JWT_SECRET:Aditya@hepJFROXcyu1XqolVEXkwj/5byy59wkTuKdoWZbEy04PygDtEcaqvr4zPco#}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.default-filters[0]=DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

gateway.public-endpoints=/api/auth/**, /oauth2/**, /login/oauth2/**, /actuator/**, /ws/**

# Route definitions are configured in GatewayConfig.java


#spring.boot.admin.client.url=http://localhost:8090
#spring.boot.admin.client.username=admin
#spring.boot.admin.client.password=admin123

spring.boot.admin.client.instance.service-base-url=http://localhost:${server.port}


management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
logging.level.org.springframework.cloud.gateway=DEBUG
